# Top-level convenience Makefile.  The real build rules live in src/Makefile
# (generated by ./configure from src/Makefile.in).

.PHONY: all bootstrap libdiff clean

all:
	$(MAKE) -C src

bootstrap:
	./bootstrap.sh

libdiff:
	./libdiff.sh

clean:
	$(MAKE) -C src clean
